### ISSUE TITLE
Doesn't open

### ISSUE THREAD

**Issue by TesDevelopment** [adikanchukov/warmenu#14]
When opening the gui I get no errors yet the gui just doesn't open.
`
WarMenu.CreateMenu("FBI", "Fleet Menu")
WarMenu.CheckBox("Show your rank only?", false)
local open = false

RegisterCommand("fleet",function(src,args)
    print("A")
    open = not open
    if open then 
        WarMenu.OpenMenu(1) 
        print("Debug: B")
    else 
        WarMenu.CloseMenu() 
        print("Debug: C")
    end
end)
`
[Screenshot of console](https://i.1nch.dev/u/QhXV8u6Kdpb5xdnk.png)

**Comment by warxander** [comment]
You are using API in a wrong way.
There should be a loop where you actually draw your menu, please check  [warmenu_demo.lua](https://github.com/warxander/warmenu/blob/master/warmenu_demo.lua) example.
