### ISSUE TITLE
InputButton Fix

### ISSUE THREAD

**Issue by NiT34ByTe** [adikanchukov/warmenu#15]
I found out there is a bug in InputButton
I managed to fix it by calling AddTextEntry()

`AddTextEntry("FMMC_MPM_NA", (windowTitleEntry and windowTitleEntry or ""))` LINE 422
and
`DisplayOnscreenKeyboard(1, 'FMMC_MPM_NA', '', defaultText or '', '', '', '', maxLength or 255)` LINE 423

**Comment by warxander** [comment]
Could you please provide code to reproduce your issue?
`windowTitleEntry` is not a window title string, it's a text entry - see [native docs.](https://docs.fivem.net/natives/?_0x00DC833F2568DBF6)

**Comment by NiT34ByTe** [comment]
Oh gotcha, sorry. i tough it was the message box title...
I am sorry 👍
