### ISSUE TITLE
Suggestion: Creation of a Disabledbutton to display texts

### ISSUE THREAD

**Issue by Lorenc95** [adikanchukov/warmenu#21]
function to create a disabled button, that is not focusable, and will just display a text / subtext.
Right now i am creating a button like so:
https://i.imgur.com/JX0qftT.png

These buttons are selectable, instead it'd be cool if they'd be semi-gray- ish and not selectable.

**Comment by warxander** [comment]
Not planned, the workaround is pretty simple though - use `~c~` for text color and do nothing on button select (or show 'Not available' tooltip, or send notification)
