### ISSUE TITLE
Controls Disabled when Displaying Menu

### ISSUE THREAD

**Issue by AverageGamerStudios** [adikanchukov/warmenu#22]
Hi! I just began using WarMenu. GREAT resource, however I noticed that when I display the menu, my melee controls disable themselves, and even when the menu is closed, it's still disabled.

**Comment by warxander** [comment]
Hi!

I'm not sure that it's `warmenu` issue since the native I'm using is `DisablePlayerFiring` during `WarMenu.Display` call (which works per frame, so it stops working when there is no opened menu).

Is it possible to provide a code which reproduces this issue?

**Comment by warxander** [comment]
Also, since you just started, I highly recommend to switch to my another GUI framework which is much more advanced and in active development nowadays:

https://github.com/warxander/vein

![image](https://github.com/warxander/warmenu/assets/9952391/2972a05e-c627-450f-b361-21331894439a)

**Comment by AverageGamerStudios** [comment]
Thanks, okay it is a firing issue. IS there a way to have it close and then have my firing back?

**Comment by AverageGamerStudios** [comment]
> Is it possible to provide a code which reproduces this issue?

This is the code

`Admin = {}
local QBCore = exports['qb-core']:GetCoreObject()

function Admin.Init(self)
    WarMenu.CreateMenu("main", "Admin Menu")

    WarMenu.SetMenuWidth("main", 0.2)
    WarMenu.SetMenuX("main", 0.75)

    WarMenu.CreateSubMenu("playerlist", "main", "Player List")
    WarMenu.CreateSubMenu("player", "main", "Player Options")
    WarMenu.CreateSubMenu("vehicle", "main", "Vehicle Options")
    WarMenu.CreateSubMenu("weapons", "main", "Weapon Options")
end

Admin:Init()

CreateThread(function ()
    while true do
        if WarMenu.IsMenuOpened("main") then
            if WarMenu.Button("Player List") then
                OpenMenu("playerlist")
            elseif WarMenu.Button("Player") then
                OpenMenu("player")
            elseif WarMenu.Button("Vehicle") then
                OpenMenu("vehicle")
            elseif WarMenu.Button("Weapons") then
                OpenMenu("weapons")
            end
        elseif WarMenu.IsMenuOpened("playerlist") then
            for i = 1, #QBCore.Functions.GetPlayers() do
                local Player = QBCore.Functions.GetPlayers()[i]
                WarMenu.Button(GetPlayerName(Player))
            end
        elseif WarMenu.IsMenuOpened("player") then
            if WarMenu.Button("Become Invisible") then

            elseif WarMenu.Button("Heal Yourself") then
                TriggerEvent("hospital:client:Revive", PlayerPedId())
            end
        elseif WarMenu.IsMenuOpened("weapons") then
            for k, v in pairs(QBCore.Shared.Weapons) do
                local pressed = WarMenu.Button(QBCore.Shared.Weapons[k].label)
                if pressed then
                    TriggerServerEvent("lib-admin:giveWeapon", QBCore.Shared.Weapons[k].name)
                end
            end
        end
        WarMenu.Display()
        Wait(0)
    end
end)

function OpenMenu(id)
    WarMenu.CloseMenu()
    WarMenu.OpenMenu(id)
end

RegisterCommand("admin", function (source, args, rawCommand)
    if not WarMenu.IsMenuOpened("main") then
        OpenMenu("main")
    else
        WarMenu.CloseMenu()
    end
end)
`

**Comment by warxander** [comment]
Each `WarMenu.IsMenuOpened()` `if`-block should contain `WarMenu.Display` at the end (that's why they were renamed to `WarMenu.Begin`/`WarMenu.End` mostly).
Currently you have the only `WarMenu.Display()` in `while-true` loop which executes each frame, which is resulted in unable to fire a gun.

**Comment by AverageGamerStudios** [comment]
I put each Display in each if statement and removed the one in the while loop, and it's still not letting me fire outside of the menu

**Comment by AverageGamerStudios** [comment]
> Hi!
> 
> I'm not sure that it's `warmenu` issue since the native I'm using is `DisablePlayerFiring` during `WarMenu.Display` call (which works per frame, so it stops working when there is no opened menu).
> 
> Is it possible to provide a code which reproduces this issue?

Hey! I am just following up on our conversation. I tried this, but even when the menu is closed, my player still cannot melee or shoot

`Admin = Admin or {}

function Admin.Initialize(self)
    WarMenu.CreateMenu("menu", "Admin Menu", "Liberty")

    WarMenu.SetMenuWidth("menu", 0.2)
    WarMenu.SetMenuX("menu", 0.9)

    WarMenu.CreateSubMenu("commands", "menu", "Commands")
    WarMenu.CreateSubMenu("utility", "menu", "Utility")
end

Admin:Initialize()

CreateThread(function ()
    while true do
        if WarMenu.IsMenuOpened("menu") then
            WarMenu.Display()
        else
            WarMenu.End()
        end
        Wait(0)
    end
end)

RegisterCommand("+admin", function ()
    if not WarMenu.IsMenuOpened("menu") then
        WarMenu.OpenMenu("menu")
    else
        WarMenu.CloseMenu()
    end
end)

RegisterKeyMapping("+admin", "Toggle Admin Menu", "keyboard", "f4")`

**Comment by warxander** [comment]
The correct code/approach is below:
```lua
CreateThread(function ()
  while true do
    if WarMenu.Begin("menu") then
      -- Your menu code here
      WarMenu.End()
    end
    Wait(0)
  end
end)
```

**Comment by AverageGamerStudios** [comment]
> The correct code/approach is below:
> 
> ```lua
> CreateThread(function ()
>   while true do
>     if WarMenu.Begin("menu") then
>       -- Your menu code here
>       WarMenu.End()
>     end
>     Wait(0)
>   end
> end)
> ```

Doesn't return melee or shooting

**Comment by warxander** [comment]
Fix all places where you are using it wrong.

**Comment by AverageGamerStudios** [comment]
> Fix all places where you are using it wrong.

Dude, you're supposed to offer support. Tell me where I am using it wrong. I gave you my entire code, tell me where I am using it wrong! Your code "fix" did not work, therefore, it's an issue with your framework

**Comment by AverageGamerStudios** [comment]
> Fix all places where you are using it wrong.

To prove this, I did a little test

https://pastebin.com/ntH1SD22

still doesnt let me punch or use guns when closed, and yes, I did type the command +closeMenu

**Comment by AverageGamerStudios** [comment]
> Fix all places where you are using it wrong.

Okay! I did your job for you. I took these three lines from WarMenu.Display()

		ClearAllHelpMessages()
		HudWeaponWheelIgnoreSelection()
		HudWeaponWheelIgnoreControlInput(true)

and then in put them in WarMenu.OpenMenu, then in WarMenu.CloseMenu(), I put them in again, but this time changed true to false on HudWeaponWheelIgnoreControlInput

Here's the NEW code if you want to integrate it :)

            function WarMenu.OpenMenu(id)
	            ClearAllHelpMessages()
	            HudWeaponWheelIgnoreSelection()
	            HudWeaponWheelIgnoreControlInput(true)
	            if id and menus[id] then
		            PlaySoundFrontend(-1, 'SELECT', 'HUD_FRONTEND_DEFAULT_SOUNDSET', true)
		            setMenuVisible(id, true, true)
	            end
            end

          function WarMenu.CloseMenu()
	          if currentMenu then
		          setMenuVisible(currentMenu.id, false)
		          optionCount = 0
		          currentKey = nil
		          PlaySoundFrontend(-1, 'QUIT', 'HUD_FRONTEND_DEFAULT_SOUNDSET', true)
	          end
	          HudWeaponWheelIgnoreControlInput(false)
          end

You're welcome :)

**Comment by warxander** [comment]
> it's an issue with your framework

I'm running the same framework and doesn't have this problem.
Glad to hear you have managed to solve it for yourself, good luck!

**Comment by AverageGamerStudios** [comment]
> > it's an issue with your framework
> 
> I'm running the same framework and doesn't have this problem. Glad to hear you have managed to solve it for yourself, good luck!

Well as you can see from the post above, I changed your script and it works, so yes, it was
