### ISSUE TITLE
Possible problem with loop: issue adding new buttons when in the menu from the client

### ISSUE THREAD

**Issue by Tnoxious** [adikanchukov/warmenu#24]
Seems to be issue adding new buttons when in menu from client,

In " warmenu_demo.lua " I try to add the button below, but it fails to stay. It does add items but hides them super quick from the menu

I also added this to the function the same problem button will disappear.

```
                  -- I added this under main part " if WarMenu.Begin('warmenuDemo') then " 
			local isPressed2 = WarMenu.Button('Button ADD', 'Subtext')
			if isPressed2 then
                        WarMenu.Button('TEST button', 'Testing it')
			end	
```
My function test

```
local function ButtonTest()
  --add
 WarMenu.Button('TEST button', 'Testing it')
end

-- in menu loop
			local isPressed2 = WarMenu.Button('Button ADD', 'Subtext')
			if isPressed2 then
                        ButtonTest()
			end	
```

Maybe the loop is causing it somehow, I'm trying to add in results from a search request, which was my main goal.

**Comment by warxander** [comment]
`isPressed2` equals to `true` during one frame only - when the button was actually pressed.
There are at least 2 approaches how to solve what are you trying to do:
1) (preffered) Use submenus
2) Store in state if `TEST button` should be visible and change it on button pressed
```lua
local showTestButton = false

--

if WarMenu.Button('Button ADD', 'Subtext') then
  showTestButton = true
end

if showTestButton then
  WarMenu.Button('TEST button', 'Testing it')
end
```
