### ISSUE TITLE
Possible to determine the currently active item?

### ISSUE THREAD

**Issue by cbzink** [adikanchukov/warmenu#7]
Is it possible to detect which item in the list the player is current on without them taking an action (e.g. checking the box, scrolling through combo box, etc) on it?

**Comment by Tempo147** [comment]
Up

**Comment by warxander** [comment]
Added in 0.9.10

**Comment by Tempo147** [comment]
Thank you very much

**Comment by Tempo147** [comment]
Just do you have discord or other ?

Le dim. 29 mars 2020 à 19:38, Nero Mahmoud <blanchearion@gmail.com> a
écrit :

> Thank you very much
>
> Le dim. 29 mars 2020 à 17:47, Alexander Dikanchukov <
