### ISSUE TITLE
Suggestion: Make a refresh/update system

### ISSUE THREAD

**Issue by Tempo147** [adikanchukov/warmenu#8]
I'm making a inventory and that determine not the current count of the items

**Comment by warxander** [comment]
Could you please explain your idea in more detailed way?

**Comment by Tempo147** [comment]
So i'm creating a inventory system and when i use/drop/give the count of my
item is not updating  as here https://streamable.com/c0xhb

**Comment by Tempo147** [comment]
Up ?
